### ISSUE TITLE
OTC requirements for review

### ISSUE THREAD

**Issue by kroeckx** [openssl/general-policies#11]
Our policy currently says:
```
All submissions must be reviewed and approved by at least two committers, one of whom must also be an OTC member. Neither of the reviewers can be the author of the submission.
```

This means that if an OTC member is the author, we also need an OTC member to review it. I'm not sure if that was intentional or not.

**Comment by levitte** [comment]
> It is intended. It is a simple approach and we will see how it works out in practice. We are not counting author as a meaningful reviewer in any context.

Uhmmm, *any context* might be a bit broad, wouldn't you say?  However, for the `openssl/openssl` repo, this is correct and what we have codified in our tools.

**Comment by levitte** [comment]
This can be closed, can it not?
