### ISSUE TITLE
Extend the primary platforms support

### ISSUE THREAD

**Issue by mattcaswell** [openssl/general-policies#12]
This issue is to hold a vote on extending the set of primary platforms listed in the platform policy:

https://www.openssl.org/policies/platformpolicy.html

The proposal is:

We should add linux-x86, linux-generic32 and linux-generic64 as primary platforms in the platform policy

**Comment by mattcaswell** [comment]
Vote: [+1]

**Comment by iamamoose** [comment]
[+1]

**Comment by kroeckx** [comment]
I'm voting +1. The platform list itself should mention on which OS and with which compiler we're actually testing them.

**Comment by paulidale** [comment]
Vote: [+1]

**Comment by levitte** [comment]
Vote: [+1]

**Comment by t-j-h** [comment]
Vote: [+1]

**Comment by paulidale** [comment]
Out [policy change policy](https://github.com/openssl/general-policies/blob/master/policies/policy-change-process.md#the-review-process) mandates changes be open for review for two weeks before voting.

Are we making an exception here?  If so, it should be noted in the vote.

**Comment by mattcaswell** [comment]
> Out [policy change policy](https://github.com/openssl/general-policies/blob/master/policies/policy-change-process.md#the-review-process) mandates changes be open for review for two weeks before voting.

That clause is specifically about pull requests for changes to policies in this repo. I saw this as just a regular vote covered only by the voting procedure policy. We haven't yet converted the platform policy on the website into a policy in the repo. But when we do I expect only policy wording to come to this repo and not the list of platforms themselves, i.e. in that sense this vote isn't really about a *policy* change its a change to the list of platforms covered by the policy.

**Comment by paulidale** [comment]
I'm not disagreeing with the outcome.  I also agree that minor platform changes (which this isn't IMO) could escape the two week review period before voting.

I very much disagree with procedure.  Nowhere in our policy change policy does it distinguish existing/old policies from new ones.  Specifically it begins with:

> This policy represents the way that any additions or changes to the existing policies are proposed, edited, finalized, and approved.

I.e. the source of the policy is not relevant and the policy change policy is unconditional.  We either need a two week editing period or an exemption to it as part of the vote.

**Comment by t-j-h** [comment]
I concur with @paulidale in that we need to follow the policies or *explicitly* vote an exception (and I do not think at all that the circumstances here warrant an exception).

This is not a critical situation and the community should have time to comment (or not) on the change. That was the idea behind making proposed changes public with sufficient time before vote so all inputs could be considered before voting begins.

**Comment by mattcaswell** [comment]
@paulidale, @t-j-h. This vote has now been opened for 20 days, i.e. more than the 2 weeks required. Should I restart the vote now that the 2 weeks have passed, or are the existing votes still valid?

**Comment by t-j-h** [comment]
I suggest you kick off the vote now that the review period has completed. I doubt anyone's vote will change - but that keeps with the policy change policy.

**Comment by mattcaswell** [comment]
Ok. I'm restarting this vote to be in accordance with the policy.

**Comment by mattcaswell** [comment]
Vote: [+1]

**Comment by levitte** [comment]
Vote: [+1]

**Comment by iamamoose** [comment]
[+1]

**Comment by paulidale** [comment]
Vote: [+1]

**Comment by kroeckx** [comment]
Still voting +1

**Comment by mattcaswell** [comment]
This vote has now closed. It passed:

````
Topic: We should add linux-x86, linux-generic32 and linux-generic64 as primary
       platforms in the platform policy
Proposed by: Matt Caswell
Issue link: https://github.com/openssl/general-policies/issues/12
Public: yes
Opened: 2022-03-22
Closed: 2022-03-23
Accepted:  yes  (for: 6, against: 0, abstained: 0, not voted: 0)

  Kurt       [+1]
  Mark       [+1]
  Matt       [+1]
  Pauli      [+1]
  Richard    [+1]
  Tim        [+1]
````

**Comment by mattcaswell** [comment]
I've created a PR in openssl/web#314 to implement this.
