### ISSUE TITLE
VOTE: selection and handling for SHA1 and RIMPEMD160

### ISSUE THREAD

**Issue by levitte** [openssl/general-policies#35]
Topic: Provider selection and handling for SHA1 and RIPEMD160 should be identical given the current understanding of algorithm specific security issues.
Proposed by: Tim

Votes recorded in <https://github.com/openssl/general-policies/blob/master/votes/vote-20221012-handling-sha1-and-ripemd160.txt>

**Comment by kroeckx** [comment]
Voting 0

**Comment by kroeckx** [comment]
This more looks like an OTC question
