### ISSUE TITLE
Release criteria

### ISSUE THREAD

**Issue by paulidale** [openssl/general-policies#5]
We need some release criteria for major, minor, patch, alpha and beta releases.
Removed from the versioning policy (wrt the web page):

## Release criteria

For a major or minor release, the following release criteria apply:

- all open GitHub issues and pull requests older than 2 weeks at the time of
  release need to be assessed for relevance to the version being released.
  Any flagged with the a milestone for the version to be released must
  be closed (see below);
- clean builds in GitHub Actions for two days and
- no open Coverity issues (not flagged as _False Positive_ or _Ignore_).

Valid reasons for closing an issue/PR with a milestone for the version
include:

- we have just now or sometime in the past fixed the issue;
- unable to reproduce (following discussion with original reporter
  if possible);
- working as intended;
- deliberate decision not to fix this issue until a later release (this
  wouldn't actually close the issue/PR but change the milestone instead) and
- not enough information and unable to contact reporter.

Exceptions require a vote by the [OTC] as per the OTC whatever.

[OTC]: https://github.com/openssl/general-policies/blob/master/policies/definitions.md#otc

**Comment by mattcaswell** [comment]
Shouldn't this issue be raised against the technical policies repo?

**Comment by paulidale** [comment]
Yeah.
