### ISSUE TITLE
The next LTS release

### ISSUE THREAD

**Issue by mattcaswell** [openssl/general-policies#9]
This issue to hold a vote on the next LTS release.

The proposal is:

We should announce that the next LTS release will be 3.0

**Comment by mattcaswell** [comment]
I am calling for a vote on the above proposal

**Comment by mattcaswell** [comment]
Vote: [+1]

**Comment by iamamoose** [comment]
[+1]

**Comment by paulidale** [comment]
Vote: [+1]

**Comment by t-j-h** [comment]
Vote: [+1]

**Comment by mattcaswell** [comment]
I should have mentioned that only OMC members are eligible to vote ;-)

**Comment by KanPlus** [comment]
> I should have mentioned that only OMC members are eligible to vote ;-)
--Got it, the invalid vote  have removed :-)

**Comment by kroeckx** [comment]
I'm voting +1

**Comment by levitte** [comment]
Vote: 0

**Comment by mattcaswell** [comment]
This vote is now closed and has passed:

````
Topic: We should announce that the next LTS release will be 3.0
Proposed by: Matt Caswell
https://github.com/openssl/general-policies/issues/9
Public: yes
Opened: 2022-02-16
Closed: 2022-02-22
Accepted:  yes  (for: 5, against: 0, abstained: 1, not voted: 0)

  Kurt       [+1]
  Mark       [+1]
  Matt       [+1]
  Pauli      [+1]
  Richard    [ 0]
  Tim        [+1]
````

I will leave this issue open until it is actually announced. We need to update the downloads page to indicate the new LTS status for 3.0, and I guess write a blog post to announce this?
